# To-do

services:
  care_database:
    build:
      context: care-database
      dockerfile: Dockerfile
    container_name: care_db
    environment:
      - POSTGRES_USER=${CARE_DB_USER:-care_user}
      - POSTGRES_PASSWORD=${CARE_DB_PASSWORD:-care_password}
      - POSTGRES_DB=${CARE_DB_NAME:-care_health}
    ports:
      - "${CARE_DB_PORT:-5432}:5432"
    restart: always
    volumes:
      - care_db_data:/var/lib/postgresql/data

  care_backend:
    build:
      context: care-backend
      dockerfile: Dockerfile
    container_name: care_backend
    depends_on:
      - care_database
    environment:
      - BACKEND_PORT=${CARE_BACKEND_PORT:-9010}
      - DATABASE_URL=postgresql://${CARE_DB_USER:-care_user}:${CARE_DB_PASSWORD:-care_password}@care_database:5432/${CARE_DB_NAME:-care_health}
      - AWS_PROFILE=${AWS_PROFILE:-Academy}
      - AWS_SDK_LOAD_CONFIG=${AWS_SDK_LOAD_CONFIG:-1}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-central-1}
      - CARE_API_KEY=${CARE_API_KEY:-}
      - CARE_API_URL_LLM=${CARE_API_URL_LLM:-https://api.openai.com/v1}
      - CARE_MODEL_LLM=${CARE_MODEL_LLM:-gpt-4o-mini}
      - CARE_API_URL_WHISPER=${CARE_API_URL_WHISPER:-https://api.openai.com/v1/audio/transcriptions}
      - CARE_MODEL_WHISPER=${CARE_MODEL_WHISPER:-whisper-1}
    volumes:
      - ~/.aws:/root/.aws
    ports:
      - "${CARE_BACKEND_PORT:-9010}:${CARE_BACKEND_PORT:-9010}"
    restart: always

  care_ui:
    build:
      context: care-ui
      dockerfile: Dockerfile
    container_name: care_ui
    depends_on:
      - care_backend
    environment:
      - CARE_BACKEND_URL=${CARE_BACKEND_URL:-http://care_backend:9010}
      - NEXT_PUBLIC_CARE_BACKEND_URL=${CARE_BACKEND_URL:-http://care_backend:9010}
    ports:
      - "${CARE_UI_PORT:-13000}:13000"
    restart: always

volumes:
  care_db_data:
